routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/admin', function () {
    return view('auth.login');
});

Auth::routes();
Route::group(['middleware' => ['web', 'auth', 'admin'], 'prefix' => 'admin'], function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('admin/home');
    Route::resource('user', App\Http\Controllers\UserController::class);
    Route::resource('settings', App\Http\Controllers\SettingsController::class);
    Route::resource('testimonial', App\Http\Controllers\TestimonialController::class);
    Route::resource('categories', App\Http\Controllers\CategoriesController::class);
    Route::resource('gallery', App\Http\Controllers\GalleryController::class);
    Route::post('gallery/frontpage/{id}', [App\Http\Controllers\GalleryController::class, 'frontpage'])->name('gallery.frontpage');
    Route::get('/categories/{id}/add-gallery',[App\Http\Controllers\CategoriesController::class, 'addGallery'])->name('categories.add-gallery');
});

Route::get('permissions', [App\Http\Controllers\HomeController::class, 'permissions'])->name('permissions');

Route::group(['middleware' => ['web']], function () {
    Route::get('/', [App\Http\Controllers\FrontendController::class, 'index'])->name('public.index');
    Route::get('/{slug}', [App\Http\Controllers\FrontendController::class, 'category'])->name('public.category');
    Route::post('/send-message', [App\Http\Controllers\FrontendController::class, 'sendMessage'])->name('send.message');

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    protected $fillable = [
        'first_name',
        'last_name',
        'image',
        'email',
        'password',
        'role_id'
    ];

    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role()
    {
        return $this->belongsTo(Roles::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Roles;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;
use App\Http\Helper\ImageStore;

class UserController extends Controller
{
    public function index()
    {
        $users = User::all();
        $data = ['users' => $users];
        return view('users.index')->with($data);
    }

    public function create()
    {
        $roles = Roles::all();
        $data = ["roles" => $roles];
        return view('users.create')->with($data);
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'first_name' => ['required', 'string', 'max:255'],
            'last_name'  => ['required', 'string', 'max:255'],
            'email'      => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password'       => ['required', 'string', 'min:8', 'confirmed'],
            'role_id'    => ['required', 'integer']
        ]);

        if ($validator->fails()) {
            return redirect('user/create')
                ->withErrors($validator)
                ->withInput();
        }
        if ($request->hasFile('image')) {
            $imageObj = new ImageStore($request, 'users');
            $image = $imageObj->imageStore();
            $input['image'] = $image;
        }

        User::create([

            'first_name' => $request->get('first_name'),
            'last_name'  => $request->get('last_name'),
            'email'      => $request->get('email'),
            'image'      => $image,
            'role_id'    => $request->get('role_id'),
            'password'   => Hash::make($request->get('password'))

        ]);

        Session::flash('flash_message', 'User successfully created!');
        $users = User::all();
        $data = ["users" => $users];
        return redirect('admin/user')->with($data);

    }

    public function show($id)
    {
        $user = User::FindOrFail($id);
        $data = ['user' => $user];
        return view('users.show')->with($data);
    }

    public function edit($id)
    {
        $user = User::FindOrFail($id);
        $roles = Roles::all();
        $data = [
            "user"  => $user,
            "roles" => $roles
        ];
        return view('users.edit')->with($data);
    }

    public function update(Request $request, User $user)
    {
        if ($request->has('password') && !empty($request->get('password'))) {
            $input['password'] = Hash::make($request->get('password'));
        } else {
            $input = $request->except(['password']);
        }

        if ($request->hasFile('image')) {
            $imageObj = new ImageStore($request, 'users');
            $image = $imageObj->imageStore();
            $input['image'] = $image;
        }
        $user->fill($input)->save();

        $users = User::all();
        $data = ['users' => $users];
        return view('users.index')->with($data);
    }

    public function destroy($id)
    {
        $user = User::FindOrFail($id);
        $user->delete();
        $users = User::all();
        $data = ["users" => $users];
        return view('users.index')->with($data);
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
            @if(Session::has('flash_message'))
                <div class="alert alert-success">
                    {{ Session::get('flash_message') }}
                </div>
            @endif
            </form>
            <div class="col-12">
                    <form action="{{ route('user.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">Upload image</label>
                        <div class="col-md-6">
                            <input id="image" type="file" name="image">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">First Name</label>
                        <div class="col-md-6">
                            <input id="first_name" type="text" class="form-control @error('first_name') is-invalid @enderror"
                                   value="{{ old('first_name') }}" name="first_name" autocomplete="first_name" required
                                   autofocus>
                            @error('first_name')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="last_name" class="col-md-4 col-form-label text-md-right">Last Name</label>
                        <div class="col-md-6">
                            <input id="last_name" type="text" class="form-control @error('last_name') is-invalid @enderror"
                                   value="{{ old('last_name') }}" name="last_name" required>
                            @error('last_name')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">Email</label>
                        <div class="col-md-6">
                            <input id="email" type="email" class="form-control @error('email') is-invalid @enderror"
                                   name="email" value="{{ old('email') }}" required>
                            @error('email')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">Password</label>
                        <div class="col-md-6">
                            <input id="name" type="password"
                                   class="form-control @error('password') is-invalid @enderror" name="password"
                                   required>
                            @error('password')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">Confirm Password</label>
                        <div class="col-md-6">
                            <input id="name" type="password" class="form-control" name="password_confirmation" required>
                        </div>
                    </div>
                        <div class="form-group row">
                            <label for="role" class="col-md-4 col-form-label text-md-right">Role</label>
                            <div class="col-md-6">
                                <select class="form-control" name="role_id" required>
                                    @foreach($roles as $role)
                                        <option value="{{ $role->id }}">{{ $role->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    <div class="form-group row">
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-fill btn-success glyphicon glyphicon-ok"></button>
                        </div>
                    </div>
                </form>
            </div>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
    @if(Session::has('flash_message'))
        <div class="alert alert-success">
            {{ Session::get('flash_message') }}
        </div>
        @endif
        </form>
        <div class="col-12">
            <form action="{{ route('user.update', $user) }}" method="post" enctype="multipart/form-data">
                {{ method_field('PUT') }}
                @csrf
                <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label text-md-right">Upload image</label>
                    <div class="col-md-6">
                        <input id="image" type="file" class="btn btn-warning" name="image">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label text-md-right">First Name</label>
                    <div class="col-md-6">
                        <input id="first_name" type="text" class="form-control"
                               value="{{ $user->first_name }}" name="first_name" autocomplete="first_name" required
                               autofocus>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="last_name" class="col-md-4 col-form-label text-md-right">Last Name</label>
                    <div class="col-md-6">
                        <input id="last_name" type="text" class="form-control "
                               value="{{ $user->last_name}}" name="last_name" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label text-md-right">Email</label>
                    <div class="col-md-6">
                        <input id="email" type="email" class="form-control"
                               name="email" value="{{ $user->email}}" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label text-md-right">Password</label>
                    <div class="col-md-6">
                        <input id="name" type="password" class="form-control" name="password">

                    </div>
                </div>
                <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label text-md-right">Confirm Password</label>
                    <div class="col-md-6">
                        <input id="name" type="password" class="form-control" name="password_confirmation">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="role" class="col-md-4 col-form-label text-md-right">Role</label>
                    <div class="col-md-6">
                        <select class="form-control" name="role_id" required>
                            @foreach($roles as $role)
                                <option value="{{ $role->id }}">{{ $role->name }}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-6">
                        <button type="submit" class="btn btn-fill btn-success glyphicon glyphicon-ok"></button>
                    </div>
                </div>
            </form>
        </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-12">

    <div class="panel panel-filled">
        <div class="panel-heading">
            <h3 style="text-align: center">Users</h3>
        </div>
        <div class="panel-body">
            <table class="table table-hover table-striped table-responsive-sm">
                <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">Full Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Created At</th>
                </tr>
                </thead>
                <tbody>
                    @foreach($users as $user)
                        <td><img class="img-rounded" width="50x" height="50px"
                                 src="/assets/img/users/thumbnails/{{ $user->image }}"
                                 alt="{{$user->first_name}}.{{ $user->last_name }}">
                        </td>
                        <td>{{ $user->first_name }} {{ $user->last_name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->created_at }}</td>
                        <td><a href="/admin/user/{{ $user->id }}/edit" class="btn btn-warning btn-circle"><i
                                    class="glyphicon glyphicon-edit"></i></a></td>
                        <td>
                            <form action="{{ route('user.destroy', $user) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger btn-circle"><i
                                        class="glyphicon glyphicon-remove"></i></button>
                            </form>
                        </td>
                <tr/>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@endsection