routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/admin', function () {
    return view('auth.login');
});

Auth::routes();
Route::group(['middleware' => ['web', 'auth', 'admin'], 'prefix' => 'admin'], function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('admin/home');
    Route::resource('user', App\Http\Controllers\UserController::class);
    Route::resource('settings', App\Http\Controllers\SettingsController::class);
    Route::resource('testimonial', App\Http\Controllers\TestimonialController::class);
    Route::resource('categories', App\Http\Controllers\CategoriesController::class);
    Route::resource('gallery', App\Http\Controllers\GalleryController::class);
    Route::post('gallery/frontpage/{id}', [App\Http\Controllers\GalleryController::class, 'frontpage'])->name('gallery.frontpage');
    Route::get('/categories/{id}/add-gallery',[App\Http\Controllers\CategoriesController::class, 'addGallery'])->name('categories.add-gallery');
});

Route::get('permissions', [App\Http\Controllers\HomeController::class, 'permissions'])->name('permissions');

Route::group(['middleware' => ['web']], function () {
    Route::get('/', [App\Http\Controllers\FrontendController::class, 'index'])->name('public.index');
    Route::get('/{slug}', [App\Http\Controllers\FrontendController::class, 'category'])->name('public.category');
    Route::post('/send-message', [App\Http\Controllers\FrontendController::class, 'sendMessage'])->name('send.message');

});

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Categories;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Http\Helper\ImageStore;
use Illuminate\Support\Str;

class CategoriesController extends Controller
{
    public function index()
    {
        $categories = Categories::getTree();
        $image = 'image';
        $data = ['categories' => $categories, $image];
        return view('categories.index')->with($data);
    }

    public function create()
    {
        $categories = Categories::getList();
        $data = ['categories' => $categories];
        return view('categories.create')->with($data);
    }

    public function store(Request $request)
    {
        $name = $request->get('name');
        $parent_id = $request->get('parent_id');
        $image = $request->get('image');
        $desc = $request->get('desc');
        $slug = Str::slug($request->get('name'));


        $imageObj = new ImageStore($request, 'categories');
        $image = $imageObj->imageStore();


        if (!isset($parent_id)) {
            $data = [
                'name' => $name,
                'image' => $image,
                'desc' => $desc,
                'slug' => $slug
            ];
            Categories::create($data);
            Session::flash('flash_message', 'Category successfully added!');
            return redirect()->back();
        }

        $category = Categories::FindOrFail($parent_id);

        Categories::create(['name' => $name, 'image' => $image, 'desc' => $desc], $category);
        Session::flash('flash_message', 'Category successfully added!');
        return redirect()->back();
    }

    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        $category = Categories::FindOrFail($id);
        $categories = Categories::getList();
        $data = ['category' => $category, 'categories' => $categories];
        return view('categories.edit')->with($data);
    }

    public function update(Request $request, $id)
    {

        $category = Categories::FindOrFail($id);

        $input = $request->all();


        if ($request->hasFile('image')) {
            $imageObj = new ImageStore($request, 'categories');
            $image = $imageObj->imageStore();
            $input['image'] = $image;
        }

        if ($request->has('name')) {
            $input['slug'] = Str::slug($request->get('name'));
        }

        $category->fill($input)->save();
        Session::flash('flash_message', 'Category successfully edited.');

        $categories = Categories::getTree();
        $data = ['categories' => $categories];
        return view('categories.index')->with($data);
    }

    public function destroy($id)
    {
        $category = Categories::FindOrFail($id);
        $category->delete();
        $categories = Categories::all();
        $data = ['categories' => $categories];
        return redirect('admin/categories')->with($data);
    }

    public function addGallery($id)
    {

        $category = Categories::FindOrFail($id);
        $data = ['category' => $category];
        return view('gallery.create')->with($data);

    }
}

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                @if(Session::has('flash_message'))
                    <div class="alert alert-success">
                        {{ Session::get('flash_message') }}
                    </div>
                @endif
            </div>
        </div>
    </div>

        <div class="row">
            <div class="col-12">
                <form action="{{ route('categories.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group row">
                        <label for="image" class="col-md-4 col-form-label text-md-right">Upload image</label>
                        <div class="col-md-6">
                            <input id="image" type="file" name="image">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">Category Name</label>
                        <div class="col-md-6">
                            <input id="name" type="text" class="form-control" name="name" autocomplete="name" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="meta_desc" class="col-md-4 col-form-label text-md-right">Category Description</label>
                        <div class="col-md-6">
                            <textarea id="catDesc" type="text" class="form-control" name="meta_desc" required></textarea>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="parent_id" class="col-md-4 col-form-label text-md-right">Subcategory</label>
                        <div class="col-md-6">
                            <select class="form-control @error('parent_id') is-invalid @enderror" name="parent_id">
                                <option value="">Main Category</option>
                                {!! $categories !!}
                            </select>
                            @error('parent_id')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>


                    <div class="form-group row">
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-success glyphicon glyphicon-ok"></button>
                        </div>
                    </div>

                </form>
            </div>
        </div>

@endsection
@section('scripts')
    <script>
        CKEDITOR.replace('catDesc');
    </script>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-lg-12  col-md-12 col-sm-12 col-xs-12 ">
        <div class="btn-group pull-right">
            <a href="/admin/gallery/{{ $category->id }}" class="btn btn-warning">View Gallery</a>
        </div>
        {!! $categories !!}
    </div>

    <div class="container">
        <div class="row">
            <div class="col-12">
                <form action="{{ route('categories.update', $category) }}" method="POST" enctype="multipart/form-data">
                    @method('PUT')
                    @csrf
                    <div class="form-group row">
                        <label for="image" class="col-md-4 col-form-label text-md-right">Upload Image</label>
                        <div class="col-md-6">
                            <input id="image" type="file" name="image">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">Category Name</label>
                        <div class="col-md-6">
                            <input id="name" type="text" class="form-control" name="name" value="{{ $category->name }}"
                                   autocomplete="name" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">Category Description</label>
                        <div class="col-md-6">
                            <textarea id="catDesc2" type="text" class="form-control" name="desc"
                                      required>{{ $category->desc }}</textarea>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="parent_id" class="col-md-4 col-form-label text-md-right">Subcategory</label>
                        <div class="col-md-6">
                            <select class="form-control @error('parent_id') is-invalid @enderror" name="parent_id">
                                <option value="">Main Category</option>
                                {!! $categories !!}
                            </select>
                            @error('parent_id')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">

                        <div class="col-md-6">
                            <button type="submit" class="btn btn-success glyphicon glyphicon-ok"></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <form action="{{ route('categories.destroy', $category) }}" method="POST">
        @csrf
        @method('DELETE')
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>

@endsection

@section('scripts')
    <script>
        $('[name=parent_id]').val({{ $category->parent_id }});
    </script>
    <script>
        CKEDITOR.replace('catDesc2');
    </script>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-lg-12  col-md-12 col-sm-12 col-xs-12 ">
        <div class="btn-group pull-right">
            <a href="/admin/categories/create" class="btn btn-success">+ Category</a>
        </div>
        {!! $categories !!}
    </div>
@endsection