routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/admin', function () {
    return view('auth.login');
});

Auth::routes();
Route::group(['middleware' => ['web', 'auth', 'admin'], 'prefix' => 'admin'], function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('admin/home');
    Route::resource('user', App\Http\Controllers\UserController::class);
    Route::resource('settings', App\Http\Controllers\SettingsController::class);
    Route::resource('testimonial', App\Http\Controllers\TestimonialController::class);
    Route::resource('categories', App\Http\Controllers\CategoriesController::class);
    Route::resource('gallery', App\Http\Controllers\GalleryController::class);
    Route::post('gallery/frontpage/{id}', [App\Http\Controllers\GalleryController::class, 'frontpage'])->name('gallery.frontpage');
    Route::get('/categories/{id}/add-gallery',[App\Http\Controllers\CategoriesController::class, 'addGallery'])->name('categories.add-gallery');
});

Route::get('permissions', [App\Http\Controllers\HomeController::class, 'permissions'])->name('permissions');

Route::group(['middleware' => ['web']], function () {
    Route::get('/', [App\Http\Controllers\FrontendController::class, 'index'])->name('public.index');
    Route::get('/{slug}', [App\Http\Controllers\FrontendController::class, 'category'])->name('public.category');
    Route::post('/send-message', [App\Http\Controllers\FrontendController::class, 'sendMessage'])->name('send.message');

});

app/Models/Settings.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Settings extends Model
{
    use HasFactory;

    protected $fillable = [
        'url',
        'address',
        'title',
        'image',
        'email',
        'phone',
        'about_us',
        'facebook',
        'meta_img',
        'meta_desc',
        'logo_white',
        'meta_title',
        'key_words',
        'lng',
        'lat'
];



}

app/Http/Controllers/SettingsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Settings;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;
use App\Http\Helper\ImageStore;


class SettingsController extends Controller
{
    public function index()
    {
        $settings = Settings::first();
        if ($settings) {
            return view('settings.index')->with(['settings' => $settings]);
        }
        return view('settings.create');
    }

    public function create()
    {
        return view('settings.create');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'url' => ['required', 'string', 'max:255'],
            'address' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255'],
            'title' => ['required', 'string', 'min:8'],
            'about_us' => ['required', 'string', 'min:8'],
            'facebook' => ['required', 'string', 'min:8'],
            'meta_desc' => ['required', 'string', 'min:8'],
            'meta_title' => ['required', 'string', 'min:8'],
            'key_words' => ['required', 'string', 'min:8'],
            'meta_img' => ['required', 'image'],
            'logo_white' => ['required', 'image'],
            'phone' => ['required', 'string', 'min:8'],
            'image' => ['required', 'image'],
        ]);

        if ($validator->fails()) {

            return redirect('settings/create')
                ->withErrors($validator)
                ->withInput();
        }


        $imageObj = new ImageStore($request, 'settings');
        $image = $imageObj->imageStore();

        $metaImgObj = new ImageStore($request, 'settings');
        $meta_image = $metaImgObj->imageStore('meta_img');


        $logoWhiteObj = new ImageStore($request, 'settings');
        $logo_white = $logoWhiteObj->imageStore('logo_white');


        Settings::create([
            'url' => $request->get('url'),
            'address' => $request->get('address'),
            'facebook' => $request->get('facebook'),
            'email' => $request->get('email'),
            'about_us' => $request->get('about_us'),
            'image' => $image,
            'meta_img' => $meta_image,
            'about_us' => $request->get('about_us'),
            'meta_desc' => $request->get('meta_desc'),
            'meta_title' => $request->get('meta_title'),
            'key_words' => $request->get('key_words'),
            'logo_white' => $logo_white,
            'phone' => $request->get('phone'),
            'title' => $request->get('title'),
            'lng' => $request->get('lng'),
            'lat' => $request->get('lat')
        ]);

        Session::flash('flash_message', 'Settings successfully created!');
        return redirect()->back();
    }

    public function edit()
    {
        $settings = Settings::first();
        $data = ['settings' => $settings];
        return view('settings.edit')->with($data);
    }

    public function update(Request $request, $id)
    {

        $settings = Settings::FindOrFail($id);
        $input = $request->all();

        if ($request->hasFile('image')) {
            $imageObj = new ImageStore($request, 'settings');
            $image = $imageObj->imageStore();
            $input['image'] = $image;
        }
        if ($request->hasFile('meta_img')) {

            $metaImgObj = new ImageStore($request, 'settings');
            $meta_image = $metaImgObj->imageStore('meta_img');
            $input['meta_img'] = $meta_image;
        }
        if ($request->hasFile('logo_white')) {

            $logoWhiteObj = new ImageStore($request, 'settings');
            $logo_white = $logoWhiteObj->imageStore('logo_white');
            $input['logo_white'] = $logo_white;
        }


        $settings->fill($input)->save();

        return view('settings.index')->with(['settings' => $settings]);
    }

    public function destroy($id)
    {
        //
    }
}

resources/views/settings/create.blade.php
@extends('layouts.app')

@section('content')
        <div class="row">
                <div class="col-12">
                    <form action="{{ route('settings.store') }}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group row">
                            <label for="image" class="col-md-4 col-form-label text-md-right">Upload Image</label>
                            <div class="col-md-6">
                                <input id="image" type="file"  name="image">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="logo_white" class="col-md-4 col-form-label text-md-right">Upload Logo White</label>
                            <div class="col-md-6">
                                <input id="logo_white" type="file"  name="logo_white">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="meta_img" class="col-md-4 col-form-label text-md-right">Upload Meta Image</label>
                            <div class="col-md-6">
                                <input id="meta_img" type="file"  name="meta_img">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="url" class="col-md-4 col-form-label text-md-right">URL</label>
                            <div class="col-md-6">
                                <input id="url" type="text" class="form-control @error('url') is-invalid @enderror"
                                       value="{{ old('url') }}" name="url" autocomplete="url" required autofocus>
                                @error('url')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="title" class="col-md-4 col-form-label text-md-right">Title</label>
                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control @error('title') is-invalid @enderror"
                                       value="{{ old('title') }}" name="title" required>
                                @error('title')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="meta_title" class="col-md-4 col-form-label text-md-right">Meta Title</label>
                            <div class="col-md-6">
                                <input id="meta_title" type="text" class="form-control @error('meta_title') is-invalid @enderror"
                                       value="{{ old('meta_title') }}" name="meta_title" required>
                                @error('meta_title')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="key_words" class="col-md-4 col-form-label text-md-right">Keywords</label>
                            <div class="col-md-6">
                                <input id="key_words" type="text" class="form-control @error('key_words') is-invalid @enderror"
                                       value="{{ old('key_words') }}" name="meta_title" required>
                                @error('key_words')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="address" class="col-md-4 col-form-label text-md-right">Address</label>
                            <div class="col-md-6">
                                <input id="address" type="text" class="form-control @error('address') is-invalid @enderror"
                                       name="address" value="{{ old('address') }}" required>
                                @error('address')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">Email</label>
                            <div class="col-md-6">
                                <input id="email" type="text"
                                       class="form-control @error('email') is-invalid @enderror" name="email" required>
                                @error('email')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="facebook" class="col-md-4 col-form-label text-md-right">Facebook</label>
                            <div class="col-md-6">
                                <input id="facebook" type="text"
                                       class="form-control @error('facebook') is-invalid @enderror" name="facebook" required>
                                @error('facebook')
                                <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="phone" class="col-md-4 col-form-label text-md-right">Phone Number</label>
                            <div class="col-md-6">
                                <input id="phone" type="text" class="form-control" name="phone" required>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="about_us" class="col-md-4 col-form-label text-md-right">About Us</label>
                            <div class="col-md-6">
                                <textarea id="about1" type="text" class="form-control" name="about_us" required></textarea>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="meta_desc" class="col-md-4 col-form-label text-md-right">Meta Description</label>
                            <div class="col-md-6">
                                <textarea id="meta_desc" type="text" class="form-control" name="meta_desc" required></textarea>
                            </div>
                        </div>
                        <div class="form-group row">
                            <input id="searchmap" class="controls" type="text" placeholder="Search Box"
                                   style="width: 400px; height: 35px;"/>
                            <div id="map" style="width: 100%; height: 400px">
                            </div>
                        </div>

                        <input type="hidden" name="lat" id="lat">
                        <input type="hidden" name="lng" id="lng">

                        <div class="form-group row">
                            <div class="col-md-6">
                                <button type="submit" class="btn btn-fill btn-success">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
        </div>
@endsection

@section('scripts')
<script>
    $(document).ready(function () {
// Google Maps
            map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: 41.9991801, lng: 21.3880133},
            zoom: 15
        });

        var marker = new google.maps.Marker({
            position: {lat: 41.9991801, lng: 21.3880133},
            map: map,
            draggable: true
        });
        var input = document.getElementById('searchmap');
        var searchBox = new google.maps.places.SearchBox(input);
        map.controls[google.maps.ControlPosition.TOP_CENTER].push(input);
        google.maps.event.addListener(searchBox, 'places_changed', function () {
            var places = searchBox.getPlaces();
            var bounds = new google.maps.LatLngBounds();
            var i, place;
            for (i = 0; place = places[i]; i++) {
                bounds.extend(place.geometry.location);
                marker.setPosition(place.geometry.location);
            }
            map.fitBounds(bounds);
            map.setZoom(8);
        });
        google.maps.event.addListener(marker, 'position_changed', function () {
            var lat = marker.getPosition().lat();
            var lng = marker.getPosition().lng();
            $('#lat').val(lat);
            $('#lng').val(lng);
        });
        $("form").bind("keypress", function (e) {
            if (e.keyCode == 13) {
                $("#searchmap").attr('value');
                //add more buttons here
                return false;
            }
        });
    });
</script>
@endsection

resources/views/settings/edit.blade.php
@extends('layouts.app')
@section('content')
            <div class="col-12">
                <form action="{{  route('settings.update', $settings) }}" method="post" enctype="multipart/form-data">
                    {{method_field('PUT')}}
                    @csrf
                    <div class="form-group row">
                        <label for="image" class="col-md-4 col-form-label text-md-right">Upload Logo</label>
                        <div class="col-md-6">
                            <input id="image" type="file"  name="image">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="logo_white" class="col-md-4 col-form-label text-md-right">Upload Logo White</label>
                        <div class="col-md-6">
                            <input id="logo_white" type="file"  name="logo_white">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="meta_img" class="col-md-4 col-form-label text-md-right">Upload Meta Image</label>
                        <div class="col-md-6">
                            <input id="meta_img" type="file"  name="meta_img">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="url" class="col-md-4 col-form-label text-md-right">URL</label>
                        <div class="col-md-6">
                            <input id="url" type="text" class="form-control @error('url') is-invalid @enderror"
                                   value="{{ $settings->url }}" name="url" autocomplete="url" required autofocus>
                            @error('url')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="title" class="col-md-4 col-form-label text-md-right">Title</label>
                        <div class="col-md-6">
                            <input id="title" type="text" class="form-control @error('title') is-invalid @enderror"
                                   value="{{ $settings->title }}" name="title" required>
                            @error('title')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="meta_title" class="col-md-4 col-form-label text-md-right">Meta Title</label>
                        <div class="col-md-6">
                            <input id="meta_title" type="text" class="form-control @error('meta_title') is-invalid @enderror"
                                   value="{{ $settings->meta_title }}" name="meta_title" required>
                            @error('meta_title')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="key_words" class="col-md-4 col-form-label text-md-right">Keywords</label>
                        <div class="col-md-6">
                            <input id="key_words" type="text" class="form-control @error('key_words') is-invalid @enderror"
                                   value="{{ $settings->key_words }}" name="key_words" required>
                            @error('key_words')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="address" class="col-md-4 col-form-label text-md-right">Address</label>
                        <div class="col-md-6">
                            <input id="address" type="text" class="form-control @error('address') is-invalid @enderror"
                                   name="address" value="{{ $settings->address }}" required>
                            @error('address')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="email" class="col-md-4 col-form-label text-md-right">Email</label>
                        <div class="col-md-6">
                            <input id="email" type="text"
                                   class="form-control @error('email') is-invalid @enderror" value="{{ $settings->email }}" name="email" required>
                            @error('email')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="facebook" class="col-md-4 col-form-label text-md-right">Facebook</label>
                        <div class="col-md-6">
                            <input id="facebook" type="text"
                                   class="form-control @error('facebook') is-invalid @enderror" value="{{ $settings->facebook }}" name="facebook" required>
                            @error('facebook')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="phone" class="col-md-4 col-form-label text-md-right">Phone Number</label>
                        <div class="col-md-6">
                            <input id="phone" type="text" class="form-control" name="phone" value="{{ $settings->phone }}" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="about_us" class="col-md-4 col-form-label text-md-right">About Us</label>
                        <div class="col-md-6">
                            <textarea id="about1" type="text" class="form-control" name="about_us">{{ $settings->about_us }}</textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="meta_desc" class="col-md-4 col-form-label text-md-right">Meta Description</label>
                        <div class="col-md-6">
                            <textarea id="meta_desc" type="text" class="form-control" name="meta_desc">{{ $settings->meta_desc }}</textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <input id="searchmap" class="controls" type="text" placeholder="Search Box"
                               style="width: 400px; height: 35px;"/>
                        <div id="map" style="width: 100%; height: 400px">
                        </div>
                    </div>

                    <input type="hidden" name="lat" id="lat" value="{{ $settings->lat }}">
                    <input type="hidden" name="lng" id="lng" value="{{ $settings->lng }}">

                    <div class="form-group row">
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-fill btn-success">Save</button>
                        </div>
                    </div>
                </form>
            </div>
@endsection
@section('scripts')
    <script>
        CKEDITOR.replace('meta_desc');
        CKEDITOR.replace('about1');
    </script>
    <script>
        $(document).ready(function () {
// Google Maps
            let latitude;
            let longitude;

            latitude =  @if($settings->lat) {{ $settings->lat }} @else 48.85 @endif;
            longitude = @if($settings->lng) {{$settings->lng}} @else 2.35 @endif;

                map = new google.maps.Map(document.getElementById('map'), {
                center: {lat: latitude, lng: longitude},
                zoom: 15
            });

            var marker = new google.maps.Marker({
                position: {lat: latitude, lng: longitude},
                map: map,
                draggable: true
            });
            var input = document.getElementById('searchmap');
            var searchBox = new google.maps.places.SearchBox(input);
            map.controls[google.maps.ControlPosition.TOP_CENTER].push(input);
            google.maps.event.addListener(searchBox, 'places_changed', function () {
                var places = searchBox.getPlaces();
                var bounds = new google.maps.LatLngBounds();
                var i, place;
                for (i = 0; place = places[i]; i++) {
                    bounds.extend(place.geometry.location);
                    marker.setPosition(place.geometry.location);
                }
                map.fitBounds(bounds);
                map.setZoom(8);
            });
            google.maps.event.addListener(marker, 'position_changed', function () {
                var lat = marker.getPosition().lat();
                var lng = marker.getPosition().lng();
                $('#lat').val(lat);
                $('#lng').val(lng);
            });
            $("form").bind("keypress", function (e) {
                if (e.keyCode == 13) {
                    $("#searchmap").attr('value');
                    //add more buttons here
                    return false;
                }
            });
        });
    </script>
@endsection