routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/admin', function () {
    return view('auth.login');
});

Auth::routes();
Route::group(['middleware' => ['web', 'auth', 'admin'], 'prefix' => 'admin'], function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('admin/home');
    Route::resource('user', App\Http\Controllers\UserController::class);
    Route::resource('settings', App\Http\Controllers\SettingsController::class);
    Route::resource('testimonial', App\Http\Controllers\TestimonialController::class);
    Route::resource('categories', App\Http\Controllers\CategoriesController::class);
    Route::resource('gallery', App\Http\Controllers\GalleryController::class);
    Route::post('gallery/frontpage/{id}', [App\Http\Controllers\GalleryController::class, 'frontpage'])->name('gallery.frontpage');
    Route::get('/categories/{id}/add-gallery',[App\Http\Controllers\CategoriesController::class, 'addGallery'])->name('categories.add-gallery');
});

Route::get('permissions', [App\Http\Controllers\HomeController::class, 'permissions'])->name('permissions');

Route::group(['middleware' => ['web']], function () {
    Route::get('/', [App\Http\Controllers\FrontendController::class, 'index'])->name('public.index');
    Route::get('/{slug}', [App\Http\Controllers\FrontendController::class, 'category'])->name('public.category');
    Route::post('/send-message', [App\Http\Controllers\FrontendController::class, 'sendMessage'])->name('send.message');

});

app/Models/Testimonial.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Testimonial extends Model
{
    use HasFactory;

    protected $table = 'testimonial';

    protected $fillable = [
        'name',
        'company_name',
        'desc',
    ];

}

app/Http/Controllers/TestimonialController.php
<?php

namespace App\Http\Controllers;

use App\Models\Testimonial;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class TestimonialController extends Controller
{

    public function index()
    {
        $testimonials = Testimonial::all();
        $data = ['testimonials' => $testimonials];
        return view('testimonial.index')->with($data);
    }

    public function create()
    {
        return view('testimonial.create');
    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'name' => ['required', 'string'],
            'desc' => ['required', 'string'],
        ]);

        if ($validator->fails()) {

            return redirect('testimonial/create')
                ->withErrors($validator)
                ->withInput();
        }
        Testimonial::create([
            'name'         => $request->get('name'),
            'company_name' => $request->get('company_name'),
            'desc'         => $request->get('desc'),
        ]);

        $testimonials = Testimonial::all();
        $data = ['testimonials' => $testimonials];
        return view('testimonial.index')->with($data);

    }


    public function edit($id)
    {
        $testimonial = Testimonial::FindOrFail($id);
        $data = ['testimonial' => $testimonial];
        return view('testimonial.edit')->with($data);
    }

    public function update(Request $request, $id)
    {
        $testimonial = Testimonial::FindOrFail($id);
        $validator = Validator::make($request->all(), [
            'name' => ['required', 'string', 'max:255'],
            'desc' => ['required', 'string']
        ]);

        if ($validator->fails()) {

            return redirect('admin/testimonial/create')
                ->withErrors($validator)
                ->withInput();
        }
        $testimonial->update([
            'name'         => $request->get('name'),
            'company_name' => $request->get('company_name'),
            'desc'         => $request->get('desc'),
        ]);

        $testimonial = Testimonial::all();
        $data = ['testimonials' => $testimonial];
        return view('testimonial.index')->with($data);
    }

    public function destroy($id)
    {
        $testimonial = Testimonial::FindOrFail($id);
        $testimonial->delete();
        $testimonials = Testimonial::all();
        $data = ["testimonials" => $testimonials];
        return view('testimonial.index')->with($data);
    }
}

resources/views/testimonial/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-12">
            @if(Session::has('flash_message'))
                <div class="alert alert-success">
                    {{ Session::get('flash_message') }}
                </div>
            @endif
            <div class="col-12">
                <form action="{{ route('testimonial.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>
                        <div class="col-md-6">
                            <input id="name" type="text" class="form-control @error('name') is-invalid @enderror"
                                   value="{{ old('name') }}" name="name" autocomplete="name" required
                                   autofocus>
                            @error('name')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="company_name" class="col-md-4 col-form-label text-md-right">Company Name</label>
                        <div class="col-md-6">
                            <input id="company_name" type="text"
                                   class="form-control @error('company_name') is-invalid @enderror"
                                   name="company_name" value="{{ old('company_name') }}">
                            @error('company_name')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="desc" class="col-md-4 col-form-label text-md-right">Description</label>
                        <div class="col-md-6">
                            <textarea id="description" type="text"
                                      class="form-control @error('desc') is-invalid @enderror" name="desc"
                                      required></textarea>
                            @error('desc')
                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-6">
                            <button type="submit" class="btn btn-fill btn-success glyphicon glyphicon-ok"></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        CKEDITOR.replace('description');
    </script>
@endsection

resources/views/testimonial/edit.blade.php
@extends('layouts.app')

@section('content')
    @if(Session::has('flash_message'))
        <div class="alert alert-success">
            {{ Session::get('flash_message') }}
        </div>
        @endif
        </form>
        <div class="col-12">
            <form action="{{ route('testimonial.update', $testimonial) }}" method="post" enctype="multipart/form-data">
                {{ method_field('PUT') }}
                @csrf
                <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label text-md-right">Name</label>
                    <div class="col-md-6">
                        <input id="name" type="text" class="form-control"
                               value="{{ $testimonial->name }}" name="name" autocomplete="name" required  autofocus >
                    </div>
                </div>
                <div class="form-group row">
                    <label for="company_name" class="col-md-4 col-form-label text-md-right">Company Name</label>
                    <div class="col-md-6">
                        <input id="company_name" type="text" class="form-control"
                               name="company_name" value="{{ $testimonial->company_name}}" required>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="desc" class="col-md-4 col-form-label text-md-right">Description</label>
                    <div class="col-md-6">
                        <textarea id="desc1" type="text"  class="form-control" name="desc">{{$testimonial->desc}}</textarea>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-6">
                        <button type="submit" class="btn btn-fill btn-primary glyphicon glyphicon-ok"></button>
                    </div>
                </div>
            </form>
        </div>
@endsection
@section('scripts')
    <script>
        CKEDITOR.replace('desc1');
    </script>
@endsection

resources/views/testimonial/index.blade.php
@extends('layouts.app')

@section('content')
    @foreach($testimonials as $testimonial)
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-filled">
                    <div class="panel-heading">
                        <div class="panel-title" style="text-align: center;">{{$testimonial->name}}</div>
                    </div>
                    <div class="panel-body">
                        <p>{!! $testimonial->desc !!}</p>
                    </div>
                    <div class="panel-footer">
                        <div class="btn-group pull-left">
                            <a href="/admin/testimonial/{{ $testimonial->id }}/edit" class="btn btn-warning btn-circle"><i
                                    class="glyphicon glyphicon-edit"></i></a>
                        </div>
                        <div class="btn-group pull-right">
                            <form action="{{ route('testimonial.destroy', $testimonial) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger btn-circle"><i
                                        class="glyphicon glyphicon-remove"></i></button>
                            </form>
                        </div>
                        <h3 style="text-align: center">{{ $testimonial->company_name }}</h3>
                    </div>
                </div>
            </div>
        </div>
    @endforeach
@endsection